import type { Waifu } from './types'

/**
 * The hall residents. Every fact traces to a published source in
 * SOURCES.md. No quotes or dates were invented.
 *
 * The hall is ordered by the state the characters were left in:
 * 1–26 alive, 27–32 fate unconfirmed, 33–39 gone.
 */
export const WAIFUS: Waifu[] = [
  {
    id: 'rem',
    image: '/portraits/rem.jpg',
    name: 'Rem',
    series: 'Re:Zero − Starting Life in Another World',
    studio: 'White Fox',
    debut: '2016',
    va: 'Inori Minase',
    tagline: 'A devoted demon maid whose loyalty becomes unconditional love',
    bio: [
      'Rem is a maid of the Roswaal mansion and the younger twin sister of Ram, belonging to the oni (demon) race with an affinity for water magic.',
      'After being freed from her deep inferiority complex toward her sister, she becomes fiercely devoted to protagonist Subaru Natsuki.',
    ],
    whyLoved: [
      'Her total, selfless devotion to Subaru resonates with fans who love an unconditional bond.',
      'Her journey from self-loathing to self-acceptance in the From Zero arc is one of the series most beloved moments.',
    ],
    quoteEn: 'Let\'s start from here. From square one... no, from zero!',
    traits: [
      { label: 'Devotion', value: 10 },
      { label: 'Courage', value: 9 },
      { label: 'Gentle strength', value: 8 },
    ],
    palette: { primary: '#5f7dff', glow: '#9fb3ff', accent: '#ffffff', secondary: '#bfd0ff' },
    motif: 'bayonet-halo',
    birth: { month: 2, day: 2 },
    order: 1,
    sources: ['en.wikipedia.org/wiki/Rem_(Re:Zero)', 'en.wikipedia.org/wiki/White_Fox', 'shapes.inc/fandom/zero/quotes'],
  },
  {
    id: 'kurisu',
    image: '/portraits/kurisu.jpg',
    name: 'Kurisu Makise',
    series: 'Steins;Gate',
    studio: 'White Fox',
    debut: '2011',
    va: 'Asami Imai',
    tagline: 'A neuroscience prodigy who falls for the mad scientist',
    bio: [
      'Kurisu Makise is an eighteen-year-old neuroscience genius and visiting researcher who becomes a member of the Future Gadget Laboratory.',
      'Dubbed Christina by Okabe, she balances sharp scientific logic with love that slowly catches up to her.',
    ],
    whyLoved: [
      'Her blend of razor-sharp intellect and gradually surfacing warmth makes her a beloved tsundere.',
      'The tragic time-travel weight of her storylines gives her science a romantic, human heart.',
    ],
    quoteEn: 'The passage of time depends entirely on where you\'re standing. Relativity theory, it\'s so romantic. But it\'s just so tragic too.',
    traits: [
      { label: 'Intellect', value: 10 },
      { label: 'Logic', value: 9 },
      { label: 'Hidden warmth', value: 7 },
    ],
    palette: { primary: '#2fd6c8', glow: '#8ff0e8', accent: '#eafffb', secondary: '#5fe0d6' },
    motif: 'time-crystal',
    birth: { month: 7, day: 25, year: 1992 },
    order: 2,
    sources: ['behindthevoiceactors.com/tv-shows/Steins-Gate', 'en.wikiquote.org/wiki/Steins;Gate', 'imdb.com/title/tt1910272/quotes'],
  },
  {
    id: 'megumin',
    image: '/portraits/megumin.jpg',
    name: 'Megumin',
    series: 'KonoSuba: God\'s Blessing on This Wonderful World!',
    studio: 'Studio Deen',
    debut: '2016',
    va: 'Rie Takahashi',
    tagline: 'A crimson demon arch wizard who loves only Explosion magic',
    bio: [
      'Megumin is a young arch wizard of the Crimson Demon Clan who has devoted her entire being to mastering the single spell Explosion.',
      'The first to join Kazuma party, she is also the protagonist of the spin-off KonoSuba: An Explosion on This Wonderful World!.',
    ],
    whyLoved: [
      'Her over-the-top, melodramatic self-introductions and dramatic flair make her endlessly entertaining.',
      'Her stubborn, almost religious dedication to Explosion despite its impracticality is endearingly comedic.',
    ],
    quoteEn: 'My name is Megumin! My calling is that of an arch wizard, who controls explosion magic, the strongest of all offensive magic.',
    traits: [
      { label: 'Explosion', value: 10 },
      { label: 'Confidence', value: 9 },
      { label: 'Dramatics', value: 10 },
    ],
    palette: { primary: '#ff3b5c', glow: '#ffb199', accent: '#ffd166', secondary: '#ff7ba9' },
    motif: 'explosion-crest',
    birth: { month: 12, day: 4 },
    order: 3,
    sources: ['konosuba.fandom.com/wiki/Megumin', 'en.wikipedia.org/wiki/Rie_Takahashi', 'en.wikipedia.org/wiki/KonoSuba'],
  },
  {
    id: 'marin',
    image: '/portraits/marin.jpg',
    name: 'Marin Kitagawa',
    series: 'My Dress-Up Darling',
    studio: 'CloverWorks',
    debut: '2022',
    va: 'Hina Suguta',
    tagline: 'A gal who dares to love what she loves openly',
    bio: [
      'Marin Kitagawa is a second-year high school student at Kikko Academy who appears to be a trendy gyaru but is secretly a passionate otaku.',
      'After discovering classmate Gojo Wakana talent for making hina doll faces, she enlists him to craft cosplay outfits, and the two slowly grow close.',
      'Her fearless enthusiasm for her interests and warm acceptance of others drive the story heart.',
    ],
    whyLoved: [
      'She breaks the gyaru stereotype by cheerfully embracing her otaku side and refusing to be ashamed of what she loves.',
      'Her direct, sunny warmth draws out the shy Wakana, making her an empowering figure for anyone who ever hid their passions.',
    ],
    quoteEn: 'I mean, when it comes to things you like, doesn\'t gender not even matter?',
    traits: [
      { label: 'Enthusiasm', value: 10 },
      { label: 'Kindness', value: 9 },
      { label: 'Industry', value: 8 },
    ],
    palette: { primary: '#ffa3c4', glow: '#ffd6e6', accent: '#a4c8ff', secondary: '#ffe0ec' },
    motif: 'ribbon-spiral',
    birth: { month: 3, day: 5 },
    order: 4,
    sources: ['en.wikipedia.org/wiki/My_Dress-Up_Darling', 'animecharactersdatabase.com/quotesbycharacter.php?line_id=276824', 'animemanga33.com/archives/37424'],
  },
  {
    id: 'holo',
    image: '/portraits/holo.jpg',
    name: 'Holo',
    series: 'Spice and Wolf',
    studio: 'Passione',
    debut: '2008',
    va: 'Ami Koshimizu',
    tagline: 'A wise wolf goddess seeking her distant homeland',
    bio: [
      'Holo is a centuries-old wolf harvest deity from Yoitsu who blessed the wheat fields of Pasloe before choosing to leave with the traveling merchant Kraft Lawrence.',
      'She presents herself as a slender girl with wolf ears and a bushy tail, but her true form is an enormous wolf.',
      'Her sharp wit and ability to tell lies by ear make her an invaluable business partner, while her loneliness gives the story its heart.',
    ],
    whyLoved: [
      'Her archaic speech and self-assured Wise Wolf persona make her one of the most charismatic heroines in anime.',
      'Beneath the confident exterior lies genuine vulnerability and fear of loneliness, creating a deeply human character.',
    ],
    quoteEn: 'I am Holo, the wise wolf.',
    traits: [
      { label: 'Wisdom', value: 10 },
      { label: 'Merchant cunning', value: 9 },
      { label: 'Loneliness', value: 7 },
    ],
    palette: { primary: '#ffb84d', glow: '#ffd98f', accent: '#fff3d6', secondary: '#e8923a' },
    motif: 'grain-field',
    order: 5,
    sources: ['en.wikipedia.org/wiki/Spice_and_Wolf', 'animecharactersdatabase.com/quotesbycharacter.php?line_id=91079', 'infobenry.com/archives/2285'],
  },
  {
    id: 'kaguya',
    image: '/portraits/kaguya.jpg',
    name: 'Kaguya Shinomiya',
    series: 'Kaguya-sama: Love Is War',
    studio: 'A-1 Pictures',
    debut: '2019',
    va: 'Aoi Koga',
    tagline: 'A genius strategist undone by her own heart',
    bio: [
      'Kaguya Shinomiya is vice president of Shuchiin Academy student council and the scion of the powerful Shinomiya family.',
      'Though her intellect rivals her rival and crush Miyuki Shirogane, she is utterly helpless at expressing her own feelings, leading to elaborate psychological battles.',
      'Her pride, intensity, and hidden softness make her one of modern romance anime most beloved leads.',
    ],
    whyLoved: [
      'She turns courtship into a cerebral game of wits in which confessing first is defeat.',
      'Her moments of vulnerability beneath flawless composure are deeply human and endearing.',
    ],
    quoteEn: 'In order for love to be equal, someone has to make the first move.',
    traits: [
      { label: 'Intellect', value: 10 },
      { label: 'Pride', value: 9 },
      { label: 'Hidden softness', value: 7 },
    ],
    palette: { primary: '#a78bfa', glow: '#d6c6ff', accent: '#ffffff', secondary: '#8b6ff0' },
    motif: 'fan-moon',
    birth: { month: 1, day: 1 },
    order: 6,
    sources: ['en.wikipedia.org/wiki/Kaguya-sama:_Love_Is_War', 'en.wikiquote.org/wiki/Kaguya-sama:_Love_Is_War', 'fandom.com/wiki/Kaguya_Shinomiya'],
  },
  {
    id: 'asuna',
    image: '/portraits/asuna.jpg',
    name: 'Asuna Yuuki',
    series: 'Sword Art Online',
    studio: 'A-1 Pictures',
    debut: '2012',
    va: 'Haruka Tomatsu',
    tagline: 'A fierce swordswoman whose love defies worlds',
    bio: [
      'Asuna Yuuki is the deuteragonist of Sword Art Online and sub-commander of the Knights of the Blood Oath, one of the game most formidable players.',
      'Trapped in the death game of Aincrad at seventeen, she forms a bond with Kirito that transcends the virtual world.',
      'Her combat skill, culinary talent, and unwavering loyalty make her one of the most iconic heroines in modern anime.',
    ],
    whyLoved: [
      'She was among the first major female leads in isekai anime defined by her own martial skill rather than only by her romance.',
      'Her willingness to risk everything for the people she loves set a powerful standard for action anime heroines.',
    ],
    quoteEn: 'Even if what you\'re doing seems futile, you still have to do it.',
    traits: [
      { label: 'Sword skill', value: 10 },
      { label: 'Resolve', value: 9 },
      { label: 'Loyalty', value: 10 },
    ],
    palette: { primary: '#ffffff', glow: '#cfe0ff', accent: '#7da2ff', secondary: '#eaf2ff' },
    motif: 'blades-cross',
    birth: { month: 9, day: 30, year: 2007 },
    order: 7,
    sources: ['en.wikipedia.org/wiki/Asuna_Yuuki', 'swordartonline.fandom.com/wiki/Asuna', 'animecharactersdatabase.com/quotesbycharacter.php?line_id=91290'],
  },
  {
    id: 'emilia',
    image: '/portraits/emilia.jpg',
    name: 'Emilia',
    series: 'Re:Zero − Starting Life in Another World',
    studio: 'White Fox',
    debut: '2016',
    va: 'Rie Takahashi',
    tagline: 'A silver-haired half-elf dreaming of a fair kingdom',
    bio: [
      'Emilia is a silver-haired half-elf who shares the appearance of the Witch of Envy and runs as a candidate for the royal throne of Lugnica.',
      'Kind and caring but reluctant to admit it, she is accompanied by the spirit Puck.',
      'She grows from isolated self-doubt toward self-worth through the devotion of those around her.',
    ],
    whyLoved: [
      'Her gentleness despite being judged by the world for her witch-like appearance earns deep sympathy.',
      'Her quiet growth toward trusting herself and others is one of the most rewarding arcs in Re:Zero.',
    ],
    quoteEn: 'Thank you, Subaru, for everything. Thank you for saving me.',
    traits: [
      { label: 'Kindness', value: 10 },
      { label: 'Perseverance', value: 8 },
      { label: 'Silver magic', value: 9 },
    ],
    palette: { primary: '#9fd8ff', glow: '#e1f4ff', accent: '#ffffff', secondary: '#6db9ff' },
    motif: 'ice-crystal',
    birth: { month: 9, day: 23 },
    order: 8,
    sources: ['en.wikiquote.org/wiki/Re:Zero', 'en.wikipedia.org/wiki/Emilia_(Re:Zero)', 'phoenix-wind.com/character/rezero_emiria.php'],
  },
  {
    id: 'kurumi',
    image: '/portraits/kurumi.jpg',
    name: 'Kurumi Tokisaki',
    series: 'Date A Live',
    studio: 'AIC PLUS+',
    debut: '2013',
    va: 'Asami Sanada',
    tagline: 'The Worst Spirit who bends time and walks her own path',
    bio: [
      'Kurumi Tokisaki is the third Spirit to appear, nicknamed the Worst Spirit for her grim methods.',
      'She commands Zafkiel, a time-manipulating Angel, and secretly seeks to erase the suffering behind the Spirits existence.',
      'Her black-and-red gothic presence hides a tragic anti-heroine depth.',
    ],
    whyLoved: [
      'Her striking gothic design and morally grey mission make her far more sympathetic than her first impression suggests.',
      'Playing with time is the theme here, and she owns every second of it with theatrical elegance.',
    ],
    quoteEn: 'No matter how big the world is, Tokisaki Kurumi is the only one who can interfere with irreversible time.',
    traits: [
      { label: 'Time control', value: 10 },
      { label: 'Elegance', value: 9 },
      { label: 'Determination', value: 10 },
    ],
    palette: { primary: '#8d1f35', glow: '#ffb3a3', accent: '#ffd166', secondary: '#c9a227' },
    motif: 'clock-hands',
    birth: { month: 6, day: 10 },
    order: 9,
    sources: ['date-a-live.fandom.com/wiki/Kurumi_Tokisaki', 'tvtropes.org/pmwiki/pmwiki.php/Quotes/DateALive', 'animecharactersdatabase.com/jp/quotesbycharacter.php?cid=54652'],
  },
  {
    id: 'taiga',
    image: '/portraits/taiga.jpg',
    name: 'Taiga Aisaka',
    series: 'Toradora!',
    studio: 'J.C.Staff',
    debut: '2008',
    va: 'Rie Kugimiya',
    tagline: 'The Palmtop Tiger, fierce on the outside, gentle within',
    bio: [
      'Taiga Aisaka is a short-tempered, small-statured first-year at Ohashi High, nicknamed the Palmtop Tiger for her ferocity.',
      'Beneath her tsundere exterior she is lonely and deeply caring toward those close to her.',
      'Her growth from guarded isolation to honest love with Ryuuji anchors the entire series.',
    ],
    whyLoved: [
      'Her iconic tsundere energy, voiced by the legendary Rie Kugimiya, is a genre-defining performance.',
      'Her slow, earned vulnerability with Ryuuji gives Toradora! its unforgettable emotional arc.',
    ],
    quoteEn: 'In this world, there\'s this thing that no one has ever seen. It\'s gentle and very sweet. If you saw it, everyone would surely want it.',
    traits: [
      { label: 'Fierce heart', value: 10 },
      { label: 'Hidden gentleness', value: 8 },
      { label: 'Loyalty', value: 9 },
    ],
    palette: { primary: '#ffb340', glow: '#ffd98f', accent: '#fff2cc', secondary: '#ff8a5c' },
    motif: 'sun-spark',
    birth: { month: 7, day: 27 },
    order: 10,
    sources: ['tora-dora.fandom.com/wiki/Taiga_Aisaka', 'en.wikiquote.org/wiki/Toradora!', 'animecharactersdatabase.com/quotesbycharacter.php?cid=15442'],
  },
  {
    id: 'hinata',
    name: 'Hinata Hyuga',
    series: 'Naruto',
    studio: 'Pierrot',
    debut: '2002',
    va: 'Nana Mizuki',
    tagline: 'A gentle heart who turned adoration into unwavering devotion',
    bio: [
      'Hinata Hyuga is a kunoichi of Konohagakure and heir to the Hyuga clan, whose quiet perseverance and Byakugan eyes hide a steel will.',
      'Her lifelong devotion to Naruto transforms her from a girl who shrank from her own power into a fierce protector of the people she loves.',
    ],
    whyLoved: [
      'Her patience and courage mirror countless fans who admired from a distance before learning to stand tall.',
      'Her bond with Naruto is one of anime most patient romances, earned over hundreds of chapters rather than gifted.',
    ],
    quoteEn: 'That is why I’m not afraid to die protecting you! Because… I love you…',
    traits: [
      { label: 'Devotion', value: 10 },
      { label: 'Gentle strength', value: 9 },
      { label: 'Byakugan sight', value: 8 },
    ],
    palette: { primary: '#5d7ce0', glow: '#b7c6ff', accent: '#ffffff', secondary: '#8fa6f5' },
    motif: 'byakugan-petal',
    birth: { month: 12, day: 27 },
    order: 11,
    sources: ['en.wikipedia.org/wiki/Hinata_Hyuga', 'naruto.fandom.com/wiki/Hinata_Hyuga', 'en.wikiquote.org/wiki/Naruto'],
  },
  {
    id: 'yor',
    name: 'Yor Forger',
    series: 'Spy × Family',
    studio: 'WIT Studio / CloverWorks',
    debut: '2022',
    va: 'Saori Hayami',
    tagline: 'A lethal assassin whose softest side is family',
    bio: [
      'Yor Forger is a legendary assassin known as the Thorn Princess who takes the cover identity of a mild housewife for Operation Strix.',
      'Clueless about ordinary family life, she pours what she learns of kindness into a fake family that becomes genuinely hers.',
    ],
    whyLoved: [
      'The gap between her flawless kills and her endearing domestic clumsiness is one of the funniest dynamics in modern anime.',
      'Her earnest desire to be a good mother and wife, despite knowing nothing about either, melts viewers who watch her put a family first.',
    ],
    quoteEn: 'It’s a little rude, but… I’ve never been interested in men. On the contrary, they make me want to kill them.',
    traits: [
      { label: 'Lethality', value: 10 },
      { label: 'Motherly love', value: 9 },
      { label: 'Naivete', value: 7 },
    ],
    palette: { primary: '#c24d6b', glow: '#ffc2d2', accent: '#ffffff', secondary: '#e08ca3' },
    motif: 'thorn-rose',
    order: 12,
    sources: ['en.wikipedia.org/wiki/Yor_Forger', 'spy-x-family.fandom.com/wiki/Yor_Forger', 'en.wikiquote.org/wiki/Spy_×_Family'],
  },
  {
    id: 'mikasa',
    name: 'Mikasa Ackerman',
    series: 'Attack on Titan',
    studio: 'WIT Studio / MAPPA',
    debut: '2013',
    va: 'Yui Ishikawa',
    tagline: 'A guardian who loved fiercely down to the last battle',
    bio: [
      'Mikasa Ackerman is one of the strongest soldiers humanity produced, carrying an Ackerman bloodline gift along with a grief she learned to armor herself in.',
      'From the scarf Eren gave her as a child to the final choice she makes as an adult, her story is measured in the people she refuses to lose.',
    ],
    whyLoved: [
      'Her fighting prowess is nearly unmatched in the series, yet every swing of her blades is motivated by devotion rather than rage.',
      'Her quiet grief and the emotional weight of her final decision redefined what a shonen heroine could carry.',
    ],
    quoteEn: 'This is a cruel world. And yet… so beautiful…',
    traits: [
      { label: 'Combat', value: 10 },
      { label: 'Protection', value: 10 },
      { label: 'Resolve', value: 9 },
    ],
    palette: { primary: '#b84a40', glow: '#ffc0a8', accent: '#ffffff', secondary: '#d98a76' },
    motif: 'scarf-wind',
    birth: { month: 2, day: 10 },
    order: 13,
    sources: ['en.wikipedia.org/wiki/Mikasa_Ackerman', 'attackontitan.fandom.com/wiki/Mikasa_Ackerman', 'en.wikiquote.org/wiki/Attack_on_Titan'],
  },
  {
    id: 'nico-robin',
    name: 'Nico Robin',
    series: 'One Piece',
    studio: 'Toei Animation',
    debut: '2001',
    va: 'Yuriko Yamaguchi',
    tagline: 'A devil-fruit scholar who finally found a home at sea',
    bio: [
      'Nico Robin is an archaeologist of the Straw Hat Pirates and the only person alive who can read the Poneglyphs that reveal the lost history.',
      'Hunted her whole life for a forbidden knowledge, she learns that being wanted can mean being wanted by people who call her family.',
    ],
    whyLoved: [
      'Her intellect and calm darkness make her a rare adult heroine in shonen, beloved for her dignity as much as her power.',
      'Enies Lobby made her refusal to be saved into one of the most quoted declarations of the will to live in anime.',
    ],
    quoteEn: 'I WANT TO LIVE! TAKE ME TO SEA WITH YOU!!!',
    traits: [
      { label: 'Knowledge', value: 10 },
      { label: 'Will to live', value: 10 },
      { label: 'Dark humor', value: 8 },
    ],
    palette: { primary: '#8a5aa8', glow: '#d2b3e8', accent: '#ffffff', secondary: '#a97ec9' },
    motif: 'devil-bloom',
    birth: { month: 2, day: 6 },
    order: 14,
    sources: ['en.wikipedia.org/wiki/Nico_Robin', 'onepiece.fandom.com/wiki/Nico_Robin', 'en.wikiquote.org/wiki/One_Piece'],
  },
  {
    id: 'rin',
    name: 'Rin Tohsaka',
    series: 'Fate/stay night',
    studio: 'ufotable',
    debut: '2006',
    va: 'Kana Ueda',
    tagline: 'A proud magus who hides softness behind rivalry',
    bio: [
      'Rin Tohsaka is a second-generation magus of the Tohsaka family competing in the Holy Grail War, brilliant, proud, and perpetually short on funds.',
      'Under the sharp tongue and the jewel magic lies a protector who would carry the world if it kept everyone she loved alive.',
    ],
    whyLoved: [
      'Her tsundere magnetism and commanding poise made her a genre staple, copied by a generation of heroines that followed.',
      'Her reluctant partnership with Shirou is built on barbed banter that slowly gives way to genuine faith — and one of anime most satisfying finales.',
    ],
    quoteEn: 'The world is just another word for the things you value around you, right? That’s something I’ve had since I was born. If you tell me to rule such a world, I already rule it.',
    traits: [
      { label: 'Pride', value: 10 },
      { label: 'Magecraft', value: 9 },
      { label: 'Hidden warmth', value: 7 },
    ],
    palette: { primary: '#d94b4b', glow: '#ffb3b3', accent: '#ffffff', secondary: '#e88080' },
    motif: 'jewel-sigil',
    birth: { month: 2, day: 3 },
    order: 15,
    sources: ['en.wikipedia.org/wiki/Rin_Tohsaka', 'typemoon.fandom.com/wiki/Rin_Tohsaka', 'en.wikiquote.org/wiki/Fate/stay_night'],
  },
  {
    id: 'chitanda',
    name: 'Chitanda Eru',
    series: 'Hyouka',
    studio: 'Kyoto Animation',
    debut: '2012',
    va: 'Satomi Sato',
    tagline: 'A curious soul who asks until the world turns over',
    bio: [
      'Chitanda Eru is the relentlessly sincere classmate who drags a retired boffin named Houtarou Oreki back into puzzles he swore he would never touch.',
      'Her boundless curiosity and earnest attention make her less an investigator than a force of nature that unearths beautiful truths.',
    ],
    whyLoved: [
      'Her politely unstoppable curiosity is one of anime most beloved character quirks, endlessly quoted and adopted.',
      'KyoAni rendered her energy so warmly that a simple request sounds like a promise of wonder.',
    ],
    quoteEn: 'I’m curious, I can’t stop thinking about it!',
    traits: [
      { label: 'Curiosity', value: 10 },
      { label: 'Perception', value: 9 },
      { label: 'Sincerity', value: 9 },
    ],
    palette: { primary: '#3f8f7c', glow: '#b8e6d8', accent: '#ffffff', secondary: '#6fb8a6' },
    motif: 'curiosity-curl',
    order: 16,
    sources: ['en.wikipedia.org/wiki/Hyouka', 'hyouka.fandom.com/wiki/Eru_Chitanda', 'en.wikiquote.org/wiki/Hyouka'],
  },
  {
    id: 'senjougahara',
    name: 'Hitagi Senjougahara',
    series: 'Monogatari',
    studio: 'Shaft',
    debut: '2009',
    va: 'Chiwa Saito',
    tagline: 'A sharp-tongued survivor whose love is spoken in absolutes',
    bio: [
      'Hitagi Senjougahara is a classmate weighed down by the crab, an apparition that took her voice and her weight along with an old trauma.',
      'Saved from her own stillness by Koyomi Araragi, she repays him by refusing to ever let him go — in her own abrasively romantic way.',
    ],
    whyLoved: [
      'Her caustic wit and deadpan threats hide one of anime most fiercely devoted romantic partners.',
      'Her arc through Monogatari turns yet another burden into a story about how love can be an act of survival.',
    ],
    quoteEn: 'By the way, Araragi-kun… I’ve never broken up with a man before. Hence, I won’t be breaking up with you either.',
    traits: [
      { label: 'Sharp tongue', value: 10 },
      { label: 'Loyalty', value: 10 },
      { label: 'Resilience', value: 9 },
    ],
    palette: { primary: '#b04a6f', glow: '#ffb8ce', accent: '#ffffff', secondary: '#d78aa4' },
    motif: 'staple-pin',
    birth: { month: 7, day: 7 },
    order: 17,
    sources: ['en.wikipedia.org/wiki/Hitagi_Senjougahara', 'en.wikiquote.org/wiki/Monogatari', 'myanimelist.net/anime/5081'],
  },
  {
    id: 'chika',
    name: 'Chika Fujiwara',
    series: 'Kaguya-sama: Love Is War',
    studio: 'A-1 Pictures',
    debut: '2019',
    va: 'Konomi Kohara',
    tagline: 'Everyone’s heroine, spilling sunshine and chaos across the council',
    bio: [
      'Chika Fujiwara is the Secretary of the Shuchiin Academy student council, a politicking family heiress whose surface is pure chaos and charm.',
      'Her cheerful incompetence at games and terrifying competence at piano make her the council’s wildcard and its heart warmer.',
    ],
    whyLoved: [
      'Author Aka Akasaka called her everyone’s heroine, and her chaotic energy is a beloved counterweight to the council’s brain wars.',
      'From Iaido panics to her trademark Chika dance, she delivers some of the most relentlessly quoted comedic moments in rom-com anime.',
    ],
    quoteEn: 'I’m used to you being bad at stuff by now. That’s how it always is, after all. It’s more important that the wonderful things in your heart reach this friend of yours.',
    traits: [
      { label: 'Chaos', value: 10 },
      { label: 'Piano talent', value: 9 },
      { label: 'Cheerful heart', value: 9 },
    ],
    palette: { primary: '#f26f9c', glow: '#ffc7da', accent: '#ffffff', secondary: '#ffa6c2' },
    motif: 'piano-heart',
    birth: { month: 3, day: 3 },
    order: 18,
    sources: ['kaguyasama-wa-kokurasetai.fandom.com/wiki/Chika_Fujiwara', 'en.wikipedia.org/wiki/Kaguya-sama:_Love_Is_War', 'en.wikiquote.org/wiki/Kaguya-sama:_Love_Is_War'],
  },
  {
    id: 'miku',
    name: 'Miku Nakano',
    series: 'The Quintessential Quintuplets',
    studio: 'Tezuka Productions / Bibury Animation Studios',
    debut: '2019',
    va: 'Miku Ito',
    tagline: 'Quietest of five, loudest with her heart',
    bio: [
      'Miku Nakano is second oldest of the quintuplets, the reserved headphone girl whose quiet sadness pays for intelligence measured in history trivia and simple kindness.',
      'Dubbed itsuki’s little sister hunter for her scientific approach to romance, she grows from self-doubt into a determined rival for the tutor’s heart.',
    ],
    whyLoved: [
      'Her quiet, stubborn pursuit of love resonates deeply with viewers who identify with the girl who never asks for the spotlight.',
      'Understated devotion, the headphones, and an earnest sincerity made her the community’s most beloved quint and the series official winner.',
    ],
    quoteEn: 'This time, for sure, I’ll be able to tell him that I love him.',
    traits: [
      { label: 'Sweetness', value: 10 },
      { label: 'Determination', value: 9 },
      { label: 'Shy warmth', value: 9 },
    ],
    palette: { primary: '#3f7fd0', glow: '#a8ccf0', accent: '#ffffff', secondary: '#71a3dc' },
    motif: 'earbud-serenade',
    birth: { month: 5, day: 5, year: 2000 },
    order: 19,
    sources: ['en.wikipedia.org/wiki/The_Quintessential_Quintuplets', '5toubun-no-hanayome.fandom.com/wiki/Miku_Nakano', 'myanimelist.net/anime/38101'],
  },
  {
    id: 'nezuko',
    name: 'Nezuko Kamado',
    series: 'Demon Slayer: Kimetsu no Yaiba',
    studio: 'ufotable',
    debut: '2019',
    va: 'Akari Kito',
    tagline: 'A demon whose humanity refuses to be extinguished',
    bio: [
      'Nezuko Kamado is Tanjiro’s little sister, turned into a demon while her family was slaughtered and rendered mute by a strange curse of her own protection.',
      'Defying everything demons are said to be, she keeps her kind heart, fighting alongside her brother rather than against him.',
    ],
    whyLoved: [
      'Her feral protectiveness paired with adorable sweetness became an instant icon of the Demon Slayer wave.',
      'A demon who refused to consume humans simply because she loves her brother too much — that devotion is the entire reason she is beloved.',
    ],
    quoteEn: 'Things don’t go exactly the way we want them to. We’re only human. You get to decide where your happiness comes from. What’s important is now.',
    traits: [
      { label: 'Protectiveness', value: 10 },
      { label: 'Resilience', value: 10 },
      { label: 'Gentleness', value: 9 },
    ],
    palette: { primary: '#f28c5c', glow: '#ffe0c0', accent: '#ffffff', secondary: '#ffbd8e' },
    motif: 'bamboo-flame',
    birth: { month: 12, day: 28 },
    order: 20,
    sources: ['en.wikipedia.org/wiki/Nezuko_Kamado', 'kimetsu-no-yaiba.fandom.com/wiki/Nezuko_Kamado', 'en.wikiquote.org/wiki/Demon_Slayer:_Kimetsu_no_Yaiba'],
  },
  {
    id: 'raphtalia',
    name: 'Raphtalia',
    series: 'The Rising of the Shield Hero',
    studio: 'Kinema Citrus',
    debut: '2019',
    va: 'Asami Seto',
    tagline: 'A blade sworn to walk every trial beside her hero',
    bio: [
      'Raphtalia is a demi-human slave girl bought by the despised Shield Hero, Naofumi Iwatani, and trained into the blade that guards his back.',
      'What begins as ownership becomes an unbreakable partnership, with her forced to grow up over years of time tampering yet choosing him afresh every day.',
    ],
    whyLoved: [
      'Her loyalty is not blind — it is a daily choice to stand beside the only person who ever treated her as worth protecting.',
      'Her growth from terrified captive to confident swordswoman, loyal and loving without losing her will, made her the heart of the Shield Hero story.',
    ],
    quoteEn: 'You are the great Shield Hero, and I am your sword. No matter how rough the path, I will follow you.',
    traits: [
      { label: 'Loyalty', value: 10 },
      { label: 'Sword skill', value: 9 },
      { label: 'Empathy', value: 9 },
    ],
    palette: { primary: '#e0714f', glow: '#ffd2bd', accent: '#ffffff', secondary: '#f09b7f' },
    motif: 'raccoon-blade',
    order: 21,
    sources: ['en.wikipedia.org/wiki/The_Rising_of_the_Shield_Hero', 'shield-hero.fandom.com/wiki/Raphtalia', 'myanimelist.net/anime/35790'],
  },
  {
    id: 'mai',
    name: 'Mai Sakurajima',
    series: 'Rascal Does Not Dream of Bunny Girl Senpai',
    studio: 'CloverWorks',
    debut: '2018',
    va: 'Asami Seto',
    tagline: 'An actress who vanished and still found him watching',
    bio: [
      'Mai Sakurajima is a former child actress retired to normal school life, the senior who haunts the library in a bunny-girl costume only one boy sees.',
      'Fading from the world through an Adolescence Syndrome, she is pulled back into existence by Sakuta’s stubborn refusal to forget her.',
    ],
    whyLoved: [
      'Her cool, sharp-tongued elegance hides a soft core, and her banter with Sakuta is some of the most beloved dialogue in recent romance anime.',
      'Her bearing under being forgotten, and her growing trust in the one person who insists, I will always find you, make her story unforgettable.',
    ],
    quoteEn: 'Forget what you saw today. Also, don’t have anything to do with me under any circumstances. If you understand, then say yes.',
    traits: [
      { label: 'Poise', value: 10 },
      { label: 'Sharp wit', value: 9 },
      { label: 'Hidden tenderness', value: 8 },
    ],
    palette: { primary: '#4d9de0', glow: '#bde3ff', accent: '#ffffff', secondary: '#7fc0f2' },
    motif: 'bunny-ear',
    birth: { month: 12, day: 2 },
    order: 22,
    sources: ['en.wikipedia.org/wiki/Rascal_Does_Not_Dream_of_Bunny_Girl_Senpai', 'en.wikiquote.org/wiki/Rascal_Does_Not_Dream_of_Bunny_Girl_Senpai', 'myanimelist.net/anime/37450'],
  },
  {
    id: 'violet',
    name: 'Violet Evergarden',
    series: 'Violet Evergarden',
    studio: 'Kyoto Animation',
    debut: '2018',
    va: 'Yui Ishikawa',
    tagline: 'A weapon learning to say what hearts mean',
    bio: [
      'Violet Evergarden is a former child soldier turned Auto Memory Doll, writing letters for others because she never learned to express herself.',
      'Through her clients’ letters she hunts for the meaning of the words I love you left to her by the major she serves.',
    ],
    whyLoved: [
      'Her arc from weapon to human is one of anime most patient and moving character studies.',
      'KyoAni’s luminous craft coupled with her quiet struggle to feel made her a beloved emblem of learning how to be loved.',
    ],
    quoteEn: 'It is a pleasure to meet you. If it is your wish, I will travel anywhere to meet your request. Auto Memory Doll, Violet Evergarden, at your service.',
    traits: [
      { label: 'Devotion', value: 10 },
      { label: 'Growth', value: 10 },
      { label: 'Sincerity', value: 10 },
    ],
    palette: { primary: '#3f8a6d', glow: '#bfe8d6', accent: '#ffffff', secondary: '#6fae90' },
    motif: 'doll-quill',
    birth: { month: 9, day: 25 },
    order: 23,
    sources: ['en.wikipedia.org/wiki/Violet_Evergarden', 'violet-evergarden.fandom.com/wiki/Violet_Evergarden', 'myanimelist.net/anime/33352'],
  },
  {
    id: 'mikoto',
    name: 'Mikoto Misaka',
    series: 'A Certain Scientific Railgun',
    studio: 'J.C.Staff',
    debut: '2008',
    va: 'Rina Sato',
    tagline: 'A level five esper who shuts down a city for what she believes in',
    bio: [
      'Mikoto Misaka is the third strongest esper in Academy City, the Railgun who flips coins at three times the speed of sound and keeps the city safe her own way.',
      'Beneath the electress bravado she quietly works to shield the weak, funding her vigilante justice through the very powers that terrify her classmates.',
    ],
    whyLoved: [
      'Her combination of overwhelming power and complete humility humbles an entire megacity of espers.',
      'Her stubborn, protective love — for her friends, her city, and the boy who shares only half her happiness — is exactly the kind of hero quality waifu rankings adore.',
    ],
    quoteEn: 'Really, what’s with that? Such a power doesn’t even appear in Academy City’s databank. If I am a 1-in-328,571 prodigy, then aren’t you, the only one in Academy City, a 1-in-2,300,000 disaster?',
    traits: [
      { label: 'Electromaster', value: 10 },
      { label: 'Justice', value: 9 },
      { label: 'City guard', value: 9 },
    ],
    palette: { primary: '#f0a63d', glow: '#ffe6b8', accent: '#ffffff', secondary: '#ffc46f' },
    motif: 'railgun-coin',
    birth: { month: 5, day: 2 },
    order: 24,
    sources: ['en.wikipedia.org/wiki/Mikoto_Misaka', 'en.wikipedia.org/wiki/A_Certain_Scientific_Railgun', 'en.wikipedia.org/wiki/A_Certain_Magical_Index'],
  },
  {
    id: 'oshino',
    name: 'Shinobu Oshino',
    series: 'Monogatari',
    studio: 'Shaft',
    debut: '2009',
    va: 'Maaya Sakamoto',
    tagline: 'An immortal vampire who chose to be human about it',
    bio: [
      'Shinobu Oshino, once the legendary vampire Kiss-Shot Acerola-Orion-Heart-Under-Blade, is bound to Koyomi Araragi after a night that should have killed them both.',
      'Reduced to a girl of unpredictable age, she lives on donuts, complains constantly, and hides five centuries of melancholy behind a serrated grin.',
    ],
    whyLoved: [
      'Her ancient wisdom against her childish petulance makes her a one-of-a-kind heroine neither girlish nor ancient.',
      'The tragic weight of her sunset that never set, and her fierce devotion to the boy who saved her by half making her a monster, endear her to every Monogatari fan.',
    ],
    quoteEn: 'It’s difficult to change the world on your own, but twisting it a little might not be all that hard.',
    traits: [
      { label: 'Immortality', value: 10 },
      { label: 'Loyalty', value: 10 },
      { label: 'Sass', value: 9 },
    ],
    palette: { primary: '#d9a441', glow: '#ffe8b0', accent: '#ffffff', secondary: '#c08a2f' },
    motif: 'bat-glint',
    order: 25,
    sources: ['en.wikipedia.org/wiki/Shinobu_Oshino', 'en.wikiquote.org/wiki/Monogatari', 'en.wikipedia.org/wiki/Monogatari_(series)'],
  },
  {
    id: 'rias',
    name: 'Rias Gremory',
    series: 'High School DxD',
    studio: 'TNK',
    debut: '2012',
    va: 'Yoko Hikasa',
    tagline: 'A crimson-haired devil who crowns her pawn with love',
    bio: [
      'Rias Gremory is a pure-blooded upper-class devil, heiress of the Gremory house, and King of a peerage she rules with grace and occasional menace.',
      'When she saves the dying Issei Hyoudou and revives him as her pawn, she sets him on a path to become a devil strong enough to stay by her side.',
    ],
    whyLoved: [
      'Her regal crimson presence, warm protectiveness, and open devotion made her the same pick as countless High School DxD fan favorites.',
      'Behind the fan-service façade lies a genuinely kind ruler who treats her servants like family and loves Issei without games or pretense.',
    ],
    quoteEn: 'My name is Rias Gremory. I am a Devil. And I am your Master. Nice to meet you, Hyoudou Issei-kun. Can I call you Ise?',
    traits: [
      { label: 'Devil pride', value: 10 },
      { label: 'Kindness', value: 9 },
      { label: 'Protectiveness', value: 10 },
    ],
    palette: { primary: '#c12638', glow: '#ffa3ad', accent: '#ffffff', secondary: '#dd6673' },
    motif: 'devil-sigil',
    birth: { month: 4, day: 9 },
    order: 26,
    sources: ['en.wikipedia.org/wiki/High_School_DxD', 'highschooldxd.fandom.com/wiki/Rias_Gremory', 'en.wikiquote.org/wiki/High_School_DxD'],
  },
  {
    id: 'zero-two',
    image: '/portraits/zero-two.jpg',
    name: 'Zero Two',
    series: 'DARLING in the FRANXX',
    studio: 'CloverWorks / Studio Trigger / A-1 Pictures',
    debut: '2018',
    va: 'Haruka Tomatsu',
    tagline: 'A hybrid klaxosaur whose fate was left to the watcher',
    bio: [
      'Zero Two, designated Code:002, is a hybrid of human and klaxosaur who pilots the FRANXX unit Strelizia.',
      'She searches for freedom and for the partner she calls her darling, a search that finally centers on Hiro.',
    ],
    whyLoved: [
      'Her fierce, predatory confidence contrasted with rare vulnerability around Hiro makes her magnetic.',
      'The star-crossed partnership she shares with Hiro is central to the series emotional impact.',
    ],
    quoteEn: 'I\'ve found you, my Darling.',
    traits: [
      { label: 'Fierce', value: 10 },
      { label: 'Playful', value: 7 },
      { label: 'Vulnerable heart', value: 6 },
    ],
    palette: { primary: '#ff5f8f', glow: '#ffb3d1', accent: '#ffd1dc', secondary: '#ff8fb2' },
    motif: 'horns-aurora',
    order: 27,
    uncertain: {
      detail: 'the anime finale implies she and Hiro return as a child beneath a sakura tree, but the series never confirms the child is either of them; in the manga she survives beside Hiro — fans remain split on which fate is canon',
    },
    sources: ['en.wikipedia.org/wiki/Darling_in_the_FranXX', 'en.cloverworks.co.jp/works/darlifra', 'darlin-franxx.fandom.com/wiki/Zero_Two'],
  },
  {
    id: 'sayaka',
    name: 'Sayaka Miki',
    series: 'Puella Magi Madoka Magica',
    studio: 'Shaft',
    debut: '2011',
    va: 'Eri Kitamura',
    tagline: 'A knight of justice whose wish cost her everything',
    bio: [
      'Sayaka Miki is Madoka’s best friend, a bright-eyed tomboy who becomes a magical girl to heal the hands of the violin prodigy she loves.',
      'Her wish for another person, and the despair she pays for it, is the series first full demonstration of how cruel the contract truly is.',
    ],
    whyLoved: [
      'Her slide from shining optimism into grief is one of anime most devastating musical strings.',
      'Even consumed by despair and turned into the witch Oktavia, her platform of a love given entirely for another struck chords with every fan of Madoka Magica.',
    ],
    quoteEn: 'I want… Kyosuke… to be able to play his violin again…',
    traits: [
      { label: 'Justice', value: 10 },
      { label: 'Self-sacrifice', value: 9 },
      { label: 'Sword magic', value: 8 },
    ],
    palette: { primary: '#3f8ad0', glow: '#bfe0ff', accent: '#ffffff', secondary: '#6fb0e8' },
    motif: 'mermaid-blade',
    order: 28,
    uncertain: {
      detail: 'she dies and becomes the witch Oktavia; in Rebellion the Law of Cycles carries every magical girl into a new existence, yet her body is never restored — sources describe her as both gone and at peace',
    },
    sources: ['en.wikipedia.org/wiki/Sayaka_Miki', 'madoka.fandom.com/wiki/Sayaka_Miki', 'en.wikiquote.org/wiki/Puella_Magi_Madoka_Magica'],
  },
  {
    id: 'madoka',
    name: 'Madoka Kaname',
    series: 'Puella Magi Madoka Magica',
    studio: 'Shaft',
    debut: '2011',
    va: 'Aoi Yuki',
    tagline: 'The one who wished to erase every tear in hope',
    bio: [
      'Madoka Kaname is the soft-spoken heart of Mitakihara, the girl whose goodness the whole tragedy circles around.',
      'Faced with a cycle of despair she inherited, she makes a wish so selfless it rewrites the rules of the universe itself.',
    ],
    whyLoved: [
      'Her gentle refusal to give up on hope, even at the price of her own existence, made her the most beloved good-girl protagonist of any modern magical anime.',
      'Her farewell to her own loved ones, absolutely quiet and absolutely selfless, is among modern anime most beautiful character exits.',
    ],
    quoteEn: 'I want to erase the tears of all those who trusted in hope… I want them to be left with a smile on their faces.',
    traits: [
      { label: 'Selflessness', value: 10 },
      { label: 'Hope', value: 10 },
      { label: 'Courage', value: 9 },
    ],
    palette: { primary: '#ff7f9e', glow: '#ffd3de', accent: '#ffffff', secondary: '#ffa3b8' },
    motif: 'pink-bow',
    birth: { month: 10, day: 3 },
    order: 29,
    uncertain: {
      detail: 'she ascends into a concept — the Law of Cycles — that quietly dissolves witches; her human existence is erased from the world and she can only return under extraordinary conditions',
    },
    sources: ['en.wikipedia.org/wiki/Madoka_Kaname', 'madoka.fandom.com/wiki/Madoka_Kaname', 'en.wikiquote.org/wiki/Puella_Magi_Madoka_Magica'],
  },
  {
    id: 'yuno',
    name: 'Yuno Gasai',
    series: 'Future Diary',
    studio: 'asread',
    debut: '2011',
    va: 'Tomosa Murata',
    tagline: 'The obsessed god candidate who writes her own future',
    bio: [
      'Yuno Gasai is the most lethal contestant in the survival game for the throne of the universe’s next God, wielding a Future Diary that sees only her own fate.',
      'Her terrifying devotion to Yukiteru Amano is interwoven with a tragic history of abuse, and her smile hides the lengths she will go to protect him.',
    ],
    whyLoved: [
      'Her unwavering, over-the-top devotion made her the defining yandere of an entire generation of anime.',
      'Behind the iconography of a knife and a smile lies a genuinely broken survivor, and that tragic depth is why so many rank her among the greats.',
    ],
    quoteEn: 'You have gotten better at kissing.',
    traits: [
      { label: 'Devotion', value: 10 },
      { label: 'Survival', value: 10 },
      { label: 'Unsteady mind', value: 8 },
    ],
    palette: { primary: '#e84a7b', glow: '#ffc0d6', accent: '#ffffff', secondary: '#f07fa0' },
    motif: 'future-diary',
    order: 30,
    uncertain: {
      detail: 'the Yuno of the original timeline dies winning godhood, while the surviving Yuno of the erased third world carries on in the Redial future — which is why sources disagree on her fate',
    },
    sources: ['en.wikipedia.org/wiki/Yuno_Gasai', 'future-diary.fandom.com/wiki/Yuno_Gasai', 'en.wikiquote.org/wiki/Future_Diary'],
  },
  {
    id: 'power',
    name: 'Power',
    series: 'Chainsaw Man',
    studio: 'MAPPA',
    debut: '2022',
    va: 'Fairouz Ai',
    tagline: 'The Blood Fiend whose loyalty outlived her body',
    bio: [
      'Power is a Blood Fiend — a devil who took over a human corpse — and the self-proclaimed greatest mind and Blood Devil of Public Safety’s Division Four.',
      'A lying, boastful force of nature who cannot stop, her brag-driven rivalry with Denji slowly becomes the most loyal friendship in the entire manga.',
    ],
    whyLoved: [
      'Her unhinged bravado and complete lack of inner filter made her the breakout chaos icon of the Chainsaw Man wave.',
      'Behind the farce she is devastatingly loyal, and her final words to Denji land like a knife to the heart of every reader.',
    ],
    quoteEn: 'Hey, hey, hey! Grovel, human!! My name is Power! Are you my buddy or whatever?!',
    traits: [
      { label: 'Chaos', value: 10 },
      { label: 'Bloody strength', value: 9 },
      { label: 'Loyalty', value: 9 },
    ],
    palette: { primary: '#dd4e3f', glow: '#ffb8a8', accent: '#ffffff', secondary: '#e88e7b' },
    motif: 'blood-hammer',
    order: 31,
    uncertain: {
      detail: 'killed by Makima, she seals a blood contract with Denji and returns arcs later as the reborn Blood Devil — alive as herself, but with no memory of him',
    },
    sources: ['en.wikipedia.org/wiki/Chainsaw_Man', 'chainsaw-man.fandom.com/wiki/Power', 'en.wikiquote.org/wiki/Chainsaw_Man'],
  },
  {
    id: 'shouko-makinohara',
    name: 'Shoko Makinohara',
    series: 'Rascal Does Not Dream of Bunny Girl Senpai',
    studio: 'CloverWorks',
    debut: '2018',
    va: 'Inori Minase',
    tagline: 'A girl who carried kindness across every timeline',
    bio: [
      'Shoko Makinohara is a middle-school girl who first meets Sakuta in a hospital stairwell, though no one else knows her name.',
      'Her rare heart condition and her Adolescence Syndrome tie her to every worldline the series visits, and her smile holds more than she ever says.',
    ],
    whyLoved: [
      'Her gentle composure in the face of a terminal countdown made Even Getting a Terminal Disease Doing Our Best look like a promise.',
      'Her refusal to let despair clip her kindness — and her selfless closing act — ranks her among the most quietly devastating heroines of the modern school-drama boom.',
    ],
    quoteEn: 'What I think, Sakuta-kun, is that life is here for us to become kinder.',
    traits: [
      { label: 'Kindness', value: 10 },
      { label: 'Sacrifice', value: 10 },
      { label: 'Smile', value: 9 },
    ],
    palette: { primary: '#77c2dd', glow: '#d8f0fa', accent: '#ffffff', secondary: '#a3d8ec' },
    motif: 'heart-stitch',
    birth: { month: 4, day: 10 },
    order: 32,
    uncertain: {
      detail: 'in the timelines they explore she dies of her congenital heart condition before the transplant date; in the worldline Sakuta finally reaches she is alive and awaiting surgery — both outcomes happen across the series',
    },
    sources: ['en.wikipedia.org/wiki/Rascal_Does_Not_Dream_of_Bunny_Girl_Senpai', 'en.wikiquote.org/wiki/Rascal_Does_Not_Dream_of_Bunny_Girl_Senpai', 'myanimelist.net/anime/37450'],
  },
  {
    id: 'sakura',
    image: '/portraits/sakura.jpg',
    name: 'Sakura Yamauchi',
    series: 'I Want to Eat Your Pancreas',
    studio: 'VOLN',
    debut: '2018',
    va: 'Lynn',
    tagline: 'A girl who chose to live loudly with the little time she had',
    bio: [
      'Sakura Yamauchi is a high school girl whose secret diary is discovered by the class loner who never spoke to anyone until he spoke to her.',
      'She lives her final months with sharp humor and enormous appetite for small joys, quietly teaching him that living is the point.',
    ],
    whyLoved: [
      'She refused self-pity, spending her last season making sure someone learned how to live.',
      'The twist of her death is what makes her story devastating and her joy unforgettable.',
    ],
    quoteEn: 'I want to eat your pancreas.',
    traits: [
      { label: 'Living loudly', value: 10 },
      { label: 'Warmth', value: 9 },
      { label: 'Courage', value: 10 },
    ],
    palette: { primary: '#ff8fa3', glow: '#ffd9e0', accent: '#ff5c9d', secondary: '#ffc4ce' },
    motif: 'petal-bloom',
    birth: { month: 3, day: 10 },
    deceased: { at: 'August 19, at 17', cause: 'a random attack after leaving the hospital' },
    order: 33,
    sources: ['en.wikipedia.org/wiki/I_Want_to_Eat_Your_Pancreas', 'en.wikipedia.org/wiki/Lynn_(voice_actress)', 'myanimelist.net/anime/33486'],
  },
  {
    id: 'kaori',
    image: '/portraits/kaori.jpg',
    name: 'Kaori Miyazono',
    series: 'Your Lie in April',
    studio: 'A-1 Pictures',
    debut: '2014',
    va: 'Risa Taneda',
    tagline: 'A violinist who poured all of spring into one song',
    bio: [
      'Kaori Miyazono is a free-spirited violinist whose chaotic, improvisational playing drags a former piano prodigy back toward the sound of life.',
      'Her hidden illness and the letter she leaves behind recast every careless note as a deliberate act of love.',
    ],
    whyLoved: [
      'She gave her brightness away so freely that her strength was only visible in hindsight.',
      'Her confession, delivered after her goodbye, is one of the most loved letters in anime.',
    ],
    quoteEn: 'Was I able to live inside someone\'s heart?',
    traits: [
      { label: 'Brilliance', value: 10 },
      { label: 'Freedom', value: 9 },
      { label: 'Hidden sorrow', value: 8 },
    ],
    palette: { primary: '#7fb5ff', glow: '#d3e6ff', accent: '#ffffff', secondary: '#a8d0ff' },
    motif: 'violin-spring',
    deceased: { at: 'February 18, at 15', cause: 'the surgery that was meant to save her failed' },
    order: 34,
    sources: ['en.wikipedia.org/wiki/Your_Lie_in_April', 'en.wikipedia.org/wiki/Risa_Taneda', 'myanimelist.net/anime/23273'],
  },
  {
    id: 'ai-hoshino',
    name: 'Ai Hoshino',
    series: 'Oshi no Ko',
    studio: 'Doga Kobo',
    debut: '2023',
    va: 'Rie Takahashi',
    tagline: 'The idol whose lies were her most honest love',
    bio: [
      'Ai Hoshino is the laughing, sparkling center of the idol group B-Komachi, drilled from birth to believe that idols are born from lies and built to be loved.',
      'Reading a sales pitch of her own stagecraft, she hides a heart denied every real connection until two people who are not quite her fans begin to mean everything.',
    ],
    whyLoved: [
      'Her transcendent onstage radiance and the quiet tragedy beneath it made her one of the most discussed heroines since the series premiered.',
      'Her final message to her twins redefines across anime what an idol’s love is allowed to be.',
    ],
    quoteEn: 'Idols are objects of worship, you know? They sparkle through the magic of lies. Lies are the most exquisite love, no?',
    traits: [
      { label: 'Radiance', value: 10 },
      { label: 'Deception', value: 10 },
      { label: 'Maternal love', value: 9 },
    ],
    palette: { primary: '#8f9ff5', glow: '#dfe4ff', accent: '#ffffff', secondary: '#b8c4ff' },
    motif: 'star-twinkle',
    order: 35,
    deceased: { at: 'at 20, right after reuniting with her twins', cause: 'she was fatally stabbed by a disgruntled fan, Ryosuke Sugano, who had been given her address' },
    sources: ['oshinoko.fandom.com/wiki/Ai_Hoshino', 'en.wikipedia.org/wiki/Oshi_no_Ko', 'en.wikiquote.org/wiki/Oshi_no_Ko'],
  },
  {
    id: 'shinobu-kocho',
    name: 'Shinobu Kocho',
    series: 'Demon Slayer: Kimetsu no Yaiba',
    studio: 'ufotable',
    debut: '2019',
    va: 'Saori Hayami',
    tagline: 'The Insect Hashira who turned venom into a smile',
    bio: [
      'Shinobu Kocho is the Insect Hashira of the Demon Slayer Corps, a master of a poison-imbued sword style, smiling always and apologizing for her bite.',
      'After her sister was devoured by a demon, she swore a plan of vengeance so patient it could only be carried by someone who smiled through grief.',
    ],
    whyLoved: [
      'Her unfailing courtesy and the blade behind it made her one of Demon Slayer most iconic dualities.',
      'Her final gambit inside the demon that killed her sister is a masterpiece of slow-burn revenge that reframes the entire Infinity Castle arc.',
    ],
    quoteEn: 'How can you feel sorry for a person that the demon ate? Shouldn’t you feel that way?',
    traits: [
      { label: 'Venom craft', value: 10 },
      { label: 'Resolve', value: 10 },
      { label: 'Hidden rage', value: 8 },
    ],
    palette: { primary: '#a78fe0', glow: '#e2d8ff', accent: '#ffffff', secondary: '#c3b8f2' },
    motif: 'butterfly-venom',
    birth: { month: 2, day: 24 },
    order: 36,
    deceased: { at: 'in the Infinity Castle, during the fight against Upper Rank Doma', cause: 'she let herself be absorbed so her own body would poison him from within for a year before her poisoned form finished him' },
    sources: ['en.wikipedia.org/wiki/Shinobu_Kocho', 'kimetsu-no-yaiba.fandom.com/wiki/Shinobu_Kocho', 'en.wikiquote.org/wiki/Demon_Slayer:_Kimetsu_no_Yaiba'],
  },
  {
    id: 'mitsuri',
    name: 'Mitsuri Kanroji',
    series: 'Demon Slayer: Kimetsu no Yaiba',
    studio: 'ufotable',
    debut: '2019',
    va: 'Kana Hanazawa',
    tagline: 'The Love Hashira who loved hard and fought harder',
    bio: [
      'Mitsuri Kanroji is the Love Hashira, whose unnatural muscle density hides beneath a soft, food-loving, romance-hounding exterior.',
      'Discovered and trained by the former Flower Hashira after being rejected for her strength, she grows into a blade of love sharp enough to cross swords with a demon lord.',
    ],
    whyLoved: [
      'Her cheerful attempts to fall in love paired with her devastating blade work make her the perfect shatter of expectations.',
      'Her refusal to let her feelings be a weakness, and her final confession beside the man who shared it, left Love Hashira fans gutted and grateful.',
    ],
    quoteEn: 'My heart would never flutter for a false love…',
    traits: [
      { label: 'Love', value: 10 },
      { label: 'Flexible blade', value: 9 },
      { label: 'Elegance', value: 9 },
    ],
    palette: { primary: '#f28ca8', glow: '#ffd3de', accent: '#ffffff', secondary: '#ffb3c4' },
    motif: 'love-petal',
    birth: { month: 6, day: 1 },
    order: 37,
    deceased: { at: 'the final battle against Muzan, at sunrise', cause: 'she fell holding the mark of a demon slayer, sharing a last confession with Obanai before the light broke' },
    sources: ['en.wikipedia.org/wiki/Mitsuri_Kanroji', 'kimetsu-no-yaiba.fandom.com/wiki/Mitsuri_Kanroji', 'en.wikiquote.org/wiki/Demon_Slayer:_Kimetsu_no_Yaiba'],
  },
  {
    id: 'esdeath',
    name: 'Esdeath',
    series: 'Akame ga Kill!',
    studio: 'White Fox',
    debut: '2014',
    va: 'Satomi Akesaka',
    tagline: 'The ice general who froze the world for her one love',
    bio: [
      'Esdeath is the Empire’s strongest general, a commander of elite warriors who believes absolutely that only the strong deserve to rule.',
      'Her obsession with the boy Tatsumi becomes the single crack in her invincibility — and the reason a woman who loved him kept the world frozen to have him.',
    ],
    whyLoved: [
      'Her ice mastery and imperial menace made her the sublimely cruel villain fans loved to rank highest among antagonists.',
      'Beneath the absolute dominance she laid a strangely pure romantic streak, one that made her last battle a matter of love as much as power.',
    ],
    quoteEn: 'The weak are destined to lie beneath the boots of the strong. If that angers you, overcome your deficits.',
    traits: [
      { label: 'Absolute power', value: 10 },
      { label: 'Hunger for strength', value: 10 },
      { label: 'Ice heart', value: 8 },
    ],
    palette: { primary: '#4fb6e0', glow: '#d0f0ff', accent: '#ffffff', secondary: '#9fe0f5' },
    motif: 'ice-blade',
    order: 38,
    deceased: { at: 'the final war, after falling to the Night Raid’s last union', cause: 'rather than yield, she froze herself solid and was shattered; no trace of her body was left' },
    sources: ['en.wikipedia.org/wiki/Akame_ga_Kill!', 'akamegakill.fandom.com/wiki/Esdeath', 'en.wikiquote.org/wiki/Akame_ga_Kill!'],
  },
  {
    id: 'mami',
    name: 'Mami Tomoe',
    series: 'Puella Magi Madoka Magica',
    studio: 'Shaft',
    debut: '2011',
    va: 'Kaori Mizuhashi',
    tagline: 'The senior who taught them to fight — and paid for it first',
    bio: [
      'Mami Tomoe is the elegant, senior magical girl of Mitakihara, who alone carries the lonely duty of hunting witches and keeping the city smiling.',
      'Her wish to live, her gift for mentorship, and her unshakeable poise make her the series’ tragic idol — and its first casualty.',
    ],
    whyLoved: [
      'Her grace under fire and her warm guidance of Madoka and Sayaka made her death the single most shining gut-punch in magical-girl anime.',
      'Her final battle remains a masterclass in how elegance can keep fighting even after everything is lost.',
    ],
    quoteEn: 'If you use your wish to grant someone else’s, you should be careful you know exactly why you’re doing it.',
    traits: [
      { label: 'Elegance', value: 10 },
      { label: 'Mentorship', value: 9 },
      { label: 'Fragile hopes', value: 8 },
    ],
    palette: { primary: '#eab952', glow: '#fff0c0', accent: '#ffffff', secondary: '#d9b04a' },
    motif: 'musket-ribbon',
    order: 39,
    deceased: { at: 'the third episode, against the witch Charlotte', cause: 'Charlotte’s second form devoured her before anyone could react; only her body from the torso up remained' },
    sources: ['en.wikipedia.org/wiki/Mami_Tomoe', 'madoka.fandom.com/wiki/Mami_Tomoe', 'wiki.puella-magi.net/Mami_Tomoe'],
  },
]