import type { Waifu } from './types'

/**
 * The twelve hall residents. Every fact traces to a published source in
 * SOURCES.md. No quotes or dates were invented.
 */
export const WAIFUS: Waifu[] = [
  {
    id: 'rem',
    name: 'Rem',
    jpName: 'レム',
    romanji: 'remu',
    series: 'Re:Zero − Starting Life in Another World',
    studio: 'White Fox',
    debut: '2016',
    va: 'Inori Minase (水瀬いのり)',
    tagline: 'A devoted demon maid whose loyalty becomes unconditional love',
    bio: [
      'Rem is a maid of the Roswaal mansion and the younger twin sister of Ram, belonging to the oni (demon) race with an affinity for water magic.',
      'After being freed from her deep inferiority complex toward her sister, she becomes fiercely devoted to protagonist Subaru Natsuki.',
    ],
    whyLoved: [
      'Her total, selfless devotion to Subaru resonates with fans who love an unconditional bond.',
      'Her journey from self-loathing to self-acceptance in the From Zero arc is one of the series most beloved moments.',
    ],
    quoteEn: 'Let\'s start from here. From square one... no, from zero!',
    quoteJp: '「ここから始めましょう——いいえ、ゼロから！」',
    traits: [
      { label: 'Devotion', value: 10 },
      { label: 'Courage', value: 9 },
      { label: 'Gentle strength', value: 8 },
    ],
    palette: { primary: '#5f7dff', glow: '#9fb3ff', accent: '#ffffff', secondary: '#bfd0ff' },
    motif: 'bayonet-halo',
    order: 1,
    sources: ['en.wikipedia.org/wiki/Rem_(Re:Zero)', 'en.wikipedia.org/wiki/White_Fox', 'shapes.inc/fandom/zero/quotes'],
  },
  {
    id: 'zero-two',
    name: 'Zero Two',
    jpName: 'ゼロツー',
    romanji: 'zero tsū',
    series: 'DARLING in the FRANXX',
    studio: 'CloverWorks / Studio Trigger / A-1 Pictures',
    debut: '2018',
    va: 'Haruka Tomatsu (戸松遥)',
    tagline: 'A hybrid klaxosaur who searches for her one true darling',
    bio: [
      'Zero Two, designated Code:002, is a hybrid of human and klaxosaur who pilots the FRANXX unit Strelizia.',
      'She searches for freedom and for the partner she calls her darling, a search that finally centers on Hiro.',
    ],
    whyLoved: [
      'Her fierce, predatory confidence contrasted with rare vulnerability around Hiro makes her magnetic.',
      'The star-crossed partnership she shares with Hiro is central to the series emotional impact.',
    ],
    quoteEn: 'I\'ve found you, my Darling.',
    quoteJp: '「やっと会えた…ダーリン…」',
    traits: [
      { label: 'Fierce', value: 10 },
      { label: 'Playful', value: 7 },
      { label: 'Vulnerable heart', value: 6 },
    ],
    palette: { primary: '#ff5f8f', glow: '#ffb3d1', accent: '#ffd1dc', secondary: '#ff8fb2' },
    motif: 'horns-aurora',
    order: 2,
    sources: ['en.wikipedia.org/wiki/Darling_in_the_FranXX', 'en.cloverworks.co.jp/works/darlifra', 'fandom.com/wiki/Episodes'],
  },
  {
    id: 'kurisu',
    name: 'Kurisu Makise',
    jpName: '牧瀬 紅莉栖',
    romanji: 'makise kurisu',
    series: 'Steins;Gate',
    studio: 'White Fox',
    debut: '2011',
    va: 'Asami Imai (今井麻美)',
    tagline: 'A neuroscience prodigy who falls for the mad scientist',
    bio: [
      'Kurisu Makise is an eighteen-year-old neuroscience genius and visiting researcher who becomes a member of the Future Gadget Laboratory.',
      'Dubbed Christina by Okabe, she balances sharp scientific logic with love that slowly catches up to her.',
    ],
    whyLoved: [
      'Her blend of razor-sharp intellect and gradually surfacing warmth makes her a beloved tsundere.',
      'The tragic time-travel weight of her storylines gives her science a romantic, human heart.',
    ],
    quoteEn: 'The passage of time depends entirely on where you\'re standing. Relativity theory, it\'s so romantic. But it\'s just so tragic too.',
    quoteJp: '「時間は人の意識によって長くなったり短くなったりする。相対性理論はとてもロマンチックで、とても切ない」',
    traits: [
      { label: 'Intellect', value: 10 },
      { label: 'Logic', value: 9 },
      { label: 'Hidden warmth', value: 7 },
    ],
    palette: { primary: '#2fd6c8', glow: '#8ff0e8', accent: '#eafffb', secondary: '#5fe0d6' },
    motif: 'time-crystal',
    order: 3,
    sources: ['behindthevoiceactors.com/tv-shows/Steins-Gate', 'en.wikiquote.org/wiki/Steins;Gate', 'imdb.com/title/tt1910272/quotes'],
  },
  {
    id: 'megumin',
    name: 'Megumin',
    jpName: 'めぐみん',
    romanji: 'megumin',
    series: 'KonoSuba: God\'s Blessing on This Wonderful World!',
    studio: 'Studio Deen',
    debut: '2016',
    va: 'Rie Takahashi (高橋李依)',
    tagline: 'A crimson demon arch wizard who loves only Explosion magic',
    bio: [
      'Megumin is a young arch wizard of the Crimson Demon Clan who has devoted her entire being to mastering the single spell Explosion.',
      'The first to join Kazuma party, she is also the protagonist of the spin-off KonoSuba: An Explosion on This Wonderful World!.',
    ],
    whyLoved: [
      'Her over-the-top chuunibyou self-introductions and dramatic flair make her endlessly entertaining.',
      'Her stubborn, almost religious dedication to Explosion despite its impracticality is endearingly comedic.',
    ],
    quoteEn: 'My name is Megumin! My calling is that of an arch wizard, who controls explosion magic, the strongest of all offensive magic.',
    quoteJp: '「我が名はめぐみん！アークウィザードを生業とし、最強の攻撃魔法、爆裂魔法を操る者！」',
    traits: [
      { label: 'Explosion', value: 10 },
      { label: 'Confidence', value: 9 },
      { label: 'Dramatics', value: 10 },
    ],
    palette: { primary: '#ff3b5c', glow: '#ffb199', accent: '#ffd166', secondary: '#ff7ba9' },
    motif: 'explosion-crest',
    order: 4,
    sources: ['konosuba.fandom.com/wiki/Megumin', 'en.wikipedia.org/wiki/Rie_Takahashi', 'en.wikipedia.org/wiki/KonoSuba'],
  },
  {
    id: 'marin',
    name: 'Marin Kitagawa',
    jpName: '喜多川海夢',
    romanji: 'kitagawa marin',
    series: 'My Dress-Up Darling',
    studio: 'CloverWorks',
    debut: '2022',
    va: 'Hina Suguta (直田姫奈)',
    tagline: 'A gal who dares to love what she loves openly',
    bio: [
      'Marin Kitagawa is a second-year high school student at Kikko Academy who appears to be a trendy gyaru but is secretly a passionate otaku.',
      'After discovering classmate Gojo Wakana talent for making hina doll faces, she enlists him to craft cosplay outfits, and the two slowly grow close.',
      'Her fearless enthusiasm for her interests and warm acceptance of others drive the story heart.',
    ],
    whyLoved: [
      'She breaks the gyaru stereotype by cheerfully embracing her otaku side and refusing to be ashamed of what she loves.',
      'Her direct, sunny warmth draws out the shy Wakana, making her an empowering figure for anyone who ever hid their passions.',
    ],
    quoteEn: 'I mean, when it comes to things you like, doesn\'t gender not even matter?',
    quoteJp: '「てゆーか、好きなものに男とか女とか関係なくない？」',
    traits: [
      { label: 'Enthusiasm', value: 10 },
      { label: 'Kindness', value: 9 },
      { label: 'Industry', value: 8 },
    ],
    palette: { primary: '#ffa3c4', glow: '#ffd6e6', accent: '#a4c8ff', secondary: '#ffe0ec' },
    motif: 'ribbon-spiral',
    order: 5,
    sources: ['en.wikipedia.org/wiki/My_Dress-Up_Darling', 'animecharactersdatabase.com/quotesbycharacter.php?line_id=276824', 'animemanga33.com/archives/37424'],
  },
  {
    id: 'holo',
    name: 'Holo',
    jpName: 'ホロ',
    romanji: 'horo',
    series: 'Spice and Wolf',
    studio: 'Passione',
    debut: '2008',
    va: 'Ami Koshimizu (小清水亜美)',
    tagline: 'A wise wolf goddess seeking her distant homeland',
    bio: [
      'Holo is a centuries-old wolf harvest deity from Yoitsu who blessed the wheat fields of Pasloe before choosing to leave with the traveling merchant Kraft Lawrence.',
      'She presents herself as a slender girl with wolf ears and a bushy tail, but her true form is an enormous wolf.',
      'Her sharp wit and ability to tell lies by ear make her an invaluable business partner, while her loneliness gives the story its heart.',
    ],
    whyLoved: [
      'Her archaic speech and self-assured Wise Wolf persona make her one of the most charismatic heroines in anime.',
      'Beneath the confident exterior lies genuine vulnerability and fear of loneliness, creating a deeply human character.',
    ],
    quoteEn: 'I am Holo, the wise wolf.',
    quoteJp: '「わっちは賢狼ホロじゃ」',
    traits: [
      { label: 'Wisdom', value: 10 },
      { label: 'Merchant cunning', value: 9 },
      { label: 'Loneliness', value: 7 },
    ],
    palette: { primary: '#ffb84d', glow: '#ffd98f', accent: '#fff3d6', secondary: '#e8923a' },
    motif: 'grain-field',
    order: 6,
    sources: ['en.wikipedia.org/wiki/Spice_and_Wolf', 'animecharactersdatabase.com/quotesbycharacter.php?line_id=91079', 'infobenry.com/archives/2285'],
  },
  {
    id: 'kaguya',
    name: 'Kaguya Shinomiya',
    jpName: '四宮かぐや',
    romanji: 'shinomiya kaguya',
    series: 'Kaguya-sama: Love Is War',
    studio: 'A-1 Pictures',
    debut: '2019',
    va: 'Aoi Koga (古賀葵)',
    tagline: 'A genius strategist undone by her own heart',
    bio: [
      'Kaguya Shinomiya is vice president of Shuchiin Academy student council and the scion of the powerful Shinomiya family.',
      'Though her intellect rivals her rival and crush Miyuki Shirogane, she is utterly helpless at expressing her own feelings, leading to elaborate psychological battles.',
      'Her pride, intensity, and hidden softness make her one of modern romance anime most beloved leads.',
    ],
    whyLoved: [
      'She turns courtship into a cerebral game of wits in which confessing first is defeat.',
      'Her moments of vulnerability beneath flawless composure are deeply human and endearing.',
    ],
    quoteEn: 'In order for love to be equal, someone has to make the first move.',
    quoteJp: '「loveは平等にしたかったのだから、最初の一歩は踏み込まなきゃ」',
    traits: [
      { label: 'Intellect', value: 10 },
      { label: 'Pride', value: 9 },
      { label: 'Hidden softness', value: 7 },
    ],
    palette: { primary: '#a78bfa', glow: '#d6c6ff', accent: '#ffffff', secondary: '#8b6ff0' },
    motif: 'fan-moon',
    order: 7,
    sources: ['en.wikipedia.org/wiki/Kaguya-sama:_Love_Is_War', 'en.wikiquote.org/wiki/Kaguya-sama:_Love_Is_War', 'fandom.com/wiki/Kaguya_Shinomiya'],
  },
  {
    id: 'asuna',
    name: 'Asuna Yuuki',
    jpName: '結城明日奈',
    romanji: 'yūki asuna',
    series: 'Sword Art Online',
    studio: 'A-1 Pictures',
    debut: '2012',
    va: 'Haruka Tomatsu (戸松遥)',
    tagline: 'A fierce swordswoman whose love defies worlds',
    bio: [
      'Asuna Yuuki is the deuteragonist of Sword Art Online and sub-commander of the Knights of the Blood Oath, one of the game most formidable players.',
      'Trapped in the death game of Aincrad at seventeen, she forms a bond with Kirito that transcends the virtual world.',
      'Her combat skill, culinary talent, and unwavering loyalty make her one of the most iconic heroines in modern anime.',
    ],
    whyLoved: [
      'She was among the first major female leads in isekai anime defined by her own martial skill rather than only by her romance.',
      'Her willingness to risk everything for the people she loves set a powerful standard for action anime heroines.',
    ],
    quoteEn: 'Even if what you\'re doing seems futile, you still have to do it.',
    quoteJp: '「たとえ無駄だとしても、やるしかないのよ」',
    traits: [
      { label: 'Sword skill', value: 10 },
      { label: 'Resolve', value: 9 },
      { label: 'Loyalty', value: 10 },
    ],
    palette: { primary: '#ffffff', glow: '#cfe0ff', accent: '#7da2ff', secondary: '#eaf2ff' },
    motif: 'blades-cross',
    order: 8,
    sources: ['en.wikipedia.org/wiki/Asuna_Yuuki', 'swordartonline.fandom.com/wiki/Asuna', 'animecharactersdatabase.com/quotesbycharacter.php?line_id=91290'],
  },
  {
    id: 'emilia',
    name: 'Emilia',
    jpName: 'エミリア',
    romanji: 'emiria',
    series: 'Re:Zero − Starting Life in Another World',
    studio: 'White Fox',
    debut: '2016',
    va: 'Rie Takahashi (高橋李依)',
    tagline: 'A silver-haired half-elf dreaming of a fair kingdom',
    bio: [
      'Emilia is a silver-haired half-elf who shares the appearance of the Witch of Envy and runs as a candidate for the royal throne of Lugnica.',
      'Kind and caring but reluctant to admit it, she is accompanied by the spirit Puck.',
      'She grows from isolated self-doubt toward self-worth through the devotion of those around her.',
    ],
    whyLoved: [
      'Her gentleness despite being judged by the world for her witch-like appearance earns deep sympathy.',
      'Her quiet growth toward trusting herself and others is one of the most rewarding arcs in Re:Zero.',
    ],
    quoteEn: 'Thank you, Subaru, for everything. Thank you for saving me.',
    quoteJp: '「ありがとう、スバル。私を助けてくれて」',
    traits: [
      { label: 'Kindness', value: 10 },
      { label: 'Perseverance', value: 8 },
      { label: 'Silver magic', value: 9 },
    ],
    palette: { primary: '#9fd8ff', glow: '#e1f4ff', accent: '#ffffff', secondary: '#6db9ff' },
    motif: 'ice-crystal',
    order: 9,
    sources: ['en.wikiquote.org/wiki/Re:Zero', 'en.wikipedia.org/wiki/Emilia_(Re:Zero)', 'phoenix-wind.com/character/rezero_emiria.php'],
  },
  {
    id: 'kurumi',
    name: 'Kurumi Tokisaki',
    jpName: '時崎 狂三',
    romanji: 'tokisaki kurumi',
    series: 'Date A Live',
    studio: 'AIC PLUS+',
    debut: '2013',
    va: 'Asami Sanada (真田アサミ)',
    tagline: 'The Worst Spirit who bends time and walks her own path',
    bio: [
      'Kurumi Tokisaki is the third Spirit to appear, nicknamed the Worst Spirit for her grim methods.',
      'She commands Zafkiel, a time-manipulating Angel, and secretly seeks to erase the suffering behind the Spirits existence.',
      'Her black-and-red gothic presence hides a tragic anti-heroine depth.',
    ],
    whyLoved: [
      'Her striking gothic design and morally grey mission make her far more sympathetic than her first impression suggests.',
      'Playing with time is the theme here, and she owns every second of it with theatrical elegance.',
    ],
    quoteEn: 'No matter how big the world is, Tokisaki Kurumi is the only one who can interfere with irreversible time.',
    quoteJp: '「世界が如何に広かろうと、不可逆の時に干渉できるのは、この時崎狂三だけですわ」',
    traits: [
      { label: 'Time control', value: 10 },
      { label: 'Elegance', value: 9 },
      { label: 'Determination', value: 10 },
    ],
    palette: { primary: '#8d1f35', glow: '#ffb3a3', accent: '#ffd166', secondary: '#c9a227' },
    motif: 'clock-hands',
    order: 10,
    sources: ['date-a-live.fandom.com/wiki/Kurumi_Tokisaki', 'tvtropes.org/pmwiki/pmwiki.php/Quotes/DateALive', 'animecharactersdatabase.com/jp/quotesbycharacter.php?cid=54652'],
  },
  {
    id: 'taiga',
    name: 'Taiga Aisaka',
    jpName: '逢坂 大河',
    romanji: 'aisaka taiga',
    series: 'Toradora!',
    studio: 'J.C.Staff',
    debut: '2008',
    va: 'Rie Kugimiya (釘宮理恵)',
    tagline: 'The Palmtop Tiger, fierce on the outside, gentle within',
    bio: [
      'Taiga Aisaka is a short-tempered, small-statured first-year at Ohashi High, nicknamed the Palmtop Tiger for her ferocity.',
      'Beneath her tsundere exterior she is lonely and deeply caring toward those close to her.',
      'Her growth from guarded isolation to honest love with Ryuuji anchors the entire series.',
    ],
    whyLoved: [
      'Her iconic tsundere energy, voiced by the legendary Rie Kugimiya, is a genre-defining performance.',
      'Her slow, earned vulnerability with Ryuuji gives Toradora! its unforgettable emotional arc.',
    ],
    quoteEn: 'In this world, there\'s this thing that no one has ever seen. It\'s gentle and very sweet. If you saw it, everyone would surely want it.',
    quoteJp: '「この世界の誰一人、見たことがないものがある。それは優しくて、とても甘い」',
    traits: [
      { label: 'Fierce heart', value: 10 },
      { label: 'Hidden gentleness', value: 8 },
      { label: 'Loyalty', value: 9 },
    ],
    palette: { primary: '#ffb340', glow: '#ffd98f', accent: '#fff2cc', secondary: '#ff8a5c' },
    motif: 'sun-spark',
    order: 11,
    sources: ['tora-dora.fandom.com/wiki/Taiga_Aisaka', 'en.wikiquote.org/wiki/Toradora!', 'animecharactersdatabase.com/quotesbycharacter.php?cid=15442'],
  },
  {
    id: 'mikasa',
    name: 'Mikasa Ackerman',
    jpName: 'ミカサ・アッカーマン',
    romanji: 'mikasa akkāman',
    series: 'Attack on Titan',
    studio: 'Wit Studio',
    debut: '2013',
    va: 'Yui Ishikawa (石川由依)',
    tagline: 'A quiet, peerless soldier whose world is cruel and beautiful',
    bio: [
      'Mikasa Ackerman is a peerless fighter of the Survey Corps and an Ackerman clan descendant gifted with extraordinary combat ability.',
      'Her world centers on protecting Eren, the family she lost and then gained.',
      'Her stoic resolve and devastating loyalty define much of the series emotional weight.',
    ],
    whyLoved: [
      'Her unmatched skill and quiet presence make her one of the most formidable soldiers in anime.',
      'The depth of her devotion to Eren gives Attack on Titan one of its most painful, resonant dynamics.',
    ],
    quoteEn: 'This world is cruel. It is also very beautiful.',
    quoteJp: '「この世界は残酷だ。そしてとても美しい」',
    traits: [
      { label: 'Combat', value: 10 },
      { label: 'Resolve', value: 9 },
      { label: 'Devotion', value: 10 },
    ],
    palette: { primary: '#e63946', glow: '#ff9ea8', accent: '#ffffff', secondary: '#ff5f7f' },
    motif: 'scarf-wind',
    order: 12,
    sources: ['en.wikipedia.org/wiki/Attack_on_Titan_(TV_series)', 'attackontitan.fandom.com/wiki/Mikasa_Ackerman', 'phraseninja.net/quote/sekai-wa-zankoku-da-soshite-totemo-utsukushii'],
  },
]